ELearning/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views
from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'', views.UserViewSet)


urlpatterns = [
    path('', views.home,name='home'),
    path('contact', views.contact,name='contact'),
    path('signup', views.sign_up,name='signup'),
    path('login', views.login,name='login'),
    path('logout', views.logout,name='logout'),
    path('course/<str:slug>/', views.course,name='course'),
    path('checkout/<str:slug>/', views.checkout,name='checkout'),
    path('verify_payment', views.verify_payment,name='verify_payment'),
    path('mycourse', views.mycourse,name='mycourse'),
    path('rest_api/', include(router.urls)),
  

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


ELearning/models.py
from django.db import models

# Create your models here.
# from  datetime import tim

class Signup(models.Model):
    first_name = models.CharField(max_length=100,default="",null=True)
    last_name = models.CharField(max_length=100,default="",null=True)
    email = models.CharField(max_length=100,default="",null=True)
    password = models.CharField(max_length=255,default="",null=True)
    mobile = models.BigIntegerField(null=True)
    gender = models.CharField(max_length=100,default="",null=True)

    def __str__(self):
        return self.first_name
    

class Course_details(models.Model):
    course_name = models.CharField(max_length=100,default="",null=True)
    slug = models.CharField(max_length=100,default="",null=True)
    desc = models.TextField(max_length=200,default="",null=True)
    price = models.IntegerField(default=1,null=True)
    discount =  models.IntegerField(default=1,null=True)
    course_image = models.ImageField(upload_to='static/images/')
    resource = models.FileField(upload_to='resources/course')
    duration  = models.TimeField()

    def __str__(self):
        return self.course_name


class Videos(models.Model):
    video_title= models.CharField(max_length=100,blank=True,null=True)
    video_id = models.CharField(max_length=100,null=True,blank=True)
    video_belong = models.ForeignKey(Course_details,on_delete=models.CASCADE,default=1)
    video_seq = models.IntegerField(null=True, blank=True)
    is_preview = models.BooleanField(default=False)

    def __str__(self):
        return self.video_title
    

class Course_info(models.Model):
    desc  = models.CharField(max_length=300, blank=True,null=True)
    course = models.ForeignKey(Course_details,on_delete=models.CASCADE)

    
    class Meta:
        abstract = True


class tag(Course_info):
    pass


class prereq(Course_info):
    pass


class learning(Course_info):
    pass


class User_Course(models.Model):
    user = models.ForeignKey(Signup,on_delete=models.CASCADE)
    course = models.ForeignKey(Course_details,on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.first_name} - {self.course.course_name}'


class Payment(models.Model):
    order_id = models.CharField(max_length=200,null=True, blank=True)
    payment_id = models.CharField(max_length=200,null=True, blank=True)
    user_info = models.ForeignKey(Signup,on_delete=models.CASCADE)
    course = models.ForeignKey(Course_details,on_delete=models.CASCADE)
    course_info = models.ForeignKey(User_Course,on_delete=models.CASCADE,null=True)
    status = models.BooleanField(default=False)


    def __str__(self):
        return self.order_id


class Ref_Code(models.Model):
    code = models.CharField(max_length=100)
    course = models.ForeignKey(Course_details,on_delete=models.CASCADE)
    discount = models.IntegerField(default=0)

    def __str__(self):
        return self.code

ELearning/templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    {% block title %}{% endblock title %}

  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

<body>
  <div class="container-fluid">
    <header class="p-3 text-bg-dark">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            <h2 class="me-5">E-Learning</h2>
          </a>

          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'home' %}" class="nav-link px-2 text-secondary">Home</a></li>
            <li><a href="{% url 'contact' %}" class="nav-link px-2 text-white">Contact</a></li>
            {% comment %} <li><a href="#" class="nav-link px-2 text-white">Course</a></li> {% endcomment %}
            {% if request.session.name %}
            <li><a href="{% url 'mycourse' %}" class="nav-link px-2 text-white">My Course</a></li>
            {% endif %}

            <li><a href="#" class="nav-link px-2 text-white">About</a></li>
          </ul>

          <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
            <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..."
              aria-label="Search">
          </form>

          <div class="text-end">
            {% if request.session.name %}
            <a href="{% url 'logout' %}" class="btn btn-outline-light me-2">
              Logout
            </a>
             <a href="/" class="btn btn-warning">
            <h6 class="">{{request.session.name}}</h6>
                </a>
            {% else %}

            <button type="button" class="btn btn-outline-light me-2" data-bs-toggle="modal" data-bs-target="#login">
              Login
            </button>
            <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#signup">
              Sign-up
            </button>
            {% endif %}

          </div>
        </div>
      </div>
    </header>
  </div>
  {% block content %}{% endblock content %}

  {% comment %} Modal for sign up {% endcomment %}
  <!-- Modal -->
  <div class="modal fade" id="signup" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Sign Up</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form class="row g-3" action="{% url 'signup' %}" method="post">
            {% csrf_token %}
            <div class="col-md-6">
              <label for="fname" class="form-label">First Name</label>
              <input type="text" class="form-control" id="fname" name="fname">
            </div>
            <div class="col-md-6">
              <label for="lname" class="form-label">Last Name</label>
              <input type="text" class="form-control" id="lname" name="lname">
            </div>
            <div class="col-md-6">
              <label for="email" class="form-label">Email</label>
              <input type="email" class="form-control" id="email" name="email">
            </div>
            <div class="col-md-6">
              <label for="password" class="form-label">Password</label>
              <input type="password" class="form-control" id="password" name="password">
            </div>
            <div class="col-md-6">
              <label for="number" class="form-label">Mobile</label>
              <input type="number" class="form-control" id="mobile" name="mobile" maxlength=10>
            </div>
            <div class="col-md-6">
              <label for="gender" class="form-label">Gender</label>
              <br>
              <input type="radio" class="form-check-input me-4" id="male" name="gender" value="male">Male
              <br>
              <input type="radio" class="form-check-input me-4" id="female" name="gender" value="female">Female
            </div>
            <div class="col-12">
              <button type="submit" class="btn btn-primary">Sign in</button>
            </div>
          </form>

        </div>

      </div>
    </div>
  </div>
  {% comment %} Modal for Login {% endcomment %}
  <!-- Modal -->
  <div class="modal fade" id="login" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Login</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <div class="row mb-3">
              <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
              <div class="col-sm-10">
                <input type="email" class="form-control" id="inputEmail3" name="email" required>
              </div>
            </div>
            <div class="row mb-3">
              <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
              <div class="col-sm-10">
                <input type="password" class="form-control" id="inputPassword3" name="password" required>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Sign in</button>
          </form>
        </div>

      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
    crossorigin="anonymous"></script>
</body>

</html>

ELearning/templates/checkout.html
{% extends 'base.html' %}
{% load calc_discount %}
{% block content %}



<div class="container my-3 text-center">
    <div class="row mx-auto border border-primary">
        <div class="col border border-primary ps-5">
            <div class="card" style="width: 18rem;">
                <img src="{{course.course_image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <p class="card-text">{{course.desc}}</p>
                </div>
            </div>
        </div>
        <div class="col border border-primary">
            <h1>{{course.course_name}}</h1>
            <div class="alert alert-primary" role="alert">
               
                {% if coup %}
                   
                  You Pay:-Rs.<h2>{% price_after_discount course.price coup.discount %}</h2>
                  <a class="btn btn-success border" href="?action=payment&coupon={{coup.code}}">Continue to Payment</a>
                  
                  {% else %}
                    You Pay:-Rs.<h2>{% price_after_discount course.price course.discount %}</h2>
                    <a class="btn btn-success border" href="?action=payment">Continue to Payment</a> 
                  {% endif %}
            </div>
           
            <form class="row g-3">
                <h2>Coupon Code:</h2>
                    {% if coupon_msg %}
                    <div class="alert alert-danger" role="alert">
                                {{coupon_msg}}!
                    </div>
                    {% elif coup %}
                    <div class="alert alert-success" role="alert">
                             You got {{coup.discount}}% discount
                    </div>
                    {% endif %}
                    <div class="col-md-6"> 
                        <input type="text" class="form-control" id="" name="coupon" placeholder="enter your coupan..">
                    </div>

               <div class="col-md-6">
                        <input type="submit" class="btn btn-primary" value="Apply Coupon" >
               </div>
                </form>
            <br>
            <br>
            {% comment %} <a href = "?action=payment" class="btn btn-primary mb-3" id="rzp-button1">Buy Now</a> {% endcomment %}


        </div>
    </div>

</div>

{% if order is not None %}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>

var options = {
    "key": "rzp_test_kWPIdUQkoNjn4P", // Enter the Key ID generated from the Dashboard
    "name": "Aptron Tech",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    'amount':"{{amount}}",
    "order_id": "{{order_id}}", 
    "callback_url": "http://localhost:8000/verify_payment",
    
    "prefill": {    
        "name": "{{user.first_name}}",
        "email": "{{user.email}}",
       
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);


    rzp1.open();


</script>
{% endif %}
{% comment %} {% endif %} {% endcomment %}

{% if error is not None %}
<script>
    alert('{{error}}')
</script>
{% endif %}
{% endblock content %} 

ELearning/templates/contact.html
{% extends 'base.html' %}

{% block title %}
Contact
{% endblock title %}

{% block content %}
<h1>THIS IS MY Contact PAGE</h1>
{% endblock content %}

ELearning/templates/course.html
{% extends 'base.html' %}

{% block title %}
Course
{% endblock title %}

{% load calc_discount %}
{% block content %}
<style>
    .curse{
        cursor:not-allowed;
    }
</style>
<div class="container my-3">
    <div class="row">
        {% comment %} {% for vid in video_fetch.Videos_set.all  %} {% endcomment %}
        <div class="col-2 my-3">
            <ul class="list-group">
            {% is_enroll request video_fetch  as enrolled %}
            {% for video_title in video_fetch.videos_set.all %}
            <li class="list-group-item {% if video_title == video %}active-video{% endif %}" aria-current="true">
                        
                    <a {% if not enrolled and not video_title.is_preview %}href="../../checkout/{{video_fetch.slug}}"{% else %}href="?serial_no={{video_title.video_seq}}" {% endif %}class="{% if video_title == video %} active-video-link {% endif %}{% if not enrolled and not video_title.is_preview %}text-muted curse {% endif %} ">{{video_title}}</a>
                       
            </li>
            {% endfor %}
          
            </ul>
        </div>
 {% comment %} {% for vid in video %} {% endcomment %}
        <div class="col-10">

            <iframe width="100%" height="495" src="https://www.youtube.com/embed/{{video.video_id}}" title="#Lec - 18 || Introduction to sql part 1 || Basic syntax of SQL || SQL queries" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

        </div>
        
        {% comment %} {% endfor %} {% endcomment %}
    </div>
    <div class="container my-3">
        <div class="row">
            <h1>Tags</h1>
            <hr>
           {% for tag in  video_fetch.tag_set.all %}
            <div class="col-12">
                {{tag.desc}}
            </div>
           {% endfor %}
        </div>
         <div class="row">
            <h1>Learning</h1>
            <hr>
           {% for tag in  video_fetch.learning_set.all %}
            <div class="col-12">
                {{tag.desc}}
            </div>
           {% endfor %}
        </div>
         <div class="row">
            <h1>Pre Req.</h1>
            <hr>
           {% for tag in  video_fetch.prereq_set.all %}
            <div class="col-12">
                {{tag.desc}}
            </div>
           {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

ELearning/templates/index.html
{% extends 'base.html' %}
{% load calc_discount %}
 {% block title %} E-Learning {% endblock title %} 
 
 {% block content %}

<div class="container my-3">
    <div class="row text-center">
        {% for crs_dtls in course_dtls %}
        <div class="col-4 text-center my-3">
            <div class="card" style="width: 18rem;">
                <img src="{{crs_dtls.course_image.url}}" class="card-img-top" alt="{{crs_dtls.course_image.url}}" height=150>
                <div class="card-body">
                    <h3 class="card-title">{{crs_dtls.course_name}}</h3>
                    <p class="card-text">{{crs_dtls.desc}}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Course Price:- <strike><strong>Rs.{{crs_dtls.price}}</strong></strike></li>
                    <li class="list-group-item">You Pay:-Rs.{% price_after_discount crs_dtls.price crs_dtls.discount %}</li>
                    <li class="list-group-item">Discount:- {{crs_dtls.discount}}%</li>
                </ul>
                <div class="card-body text-center">
                    {% is_enroll request crs_dtls as enrolled %} 
                    {% if enrolled %}
                    <a href="course/{{crs_dtls.slug}}" 
                    {% if  not request.session.name %} data-bs-toggle="modal" data-bs-target="#login"{% endif %} 
                    class="card-link btn btn-primary">Enrolled</a>

                    {% else %}
                    <a href="checkout/{{crs_dtls.slug}}/" 
                    {% if  not request.session.name %} data-bs-toggle="modal" data-bs-target="#login"{% endif %} 
                    class="card-link btn btn-primary">Enroll</a>
                    <a href="course/{{crs_dtls.slug}}/" class="card-link btn btn-primary">More</a>
                    {% endif %}
                </div>
            </div>
        </div>

        {% endfor %}
    </div>

</div>

{% endblock content %}

ELearning/templates/mycourse.html
{% extends 'base.html' %}

{% block title %}
My Course
{% endblock title %}

{% block content %}

<div class="container">
     <p class="display-6">My Courses </p>
    <hr> 
      <div class="row">
    {% for uc in user_course %}
    <div class="col">
        <div class="card mx-auto" style="width: 18rem;">
            <img src=" {{uc.course.course_image.url}}" class="card-img-top" alt="..." height=200>
            <div class="card-body">
                <h5 class="card-title">{{uc.course.name}}</h5>
                <h5 class="card-title">{{uc.course.desc}}</h5>
            </div>
            <div class="card-footer p-4">
                <div class="row no-gutters text-center">
                    <div class="col border-right">
                        <a href="course/{{uc.course.slug}}" class="btn btn-primary btn-block mystyle">Start Course</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
    {% endfor %}


</div>
</div>


{% endblock content %}